add run apps of currently focussed vm and dmenu background coloring
raffaeleflorio/qubes-dmenu pull request #2
Opened 2022-03-30 09:26 UTC by jampe

- implement dmenu_path vm command allowing you to run apps of the currently focussed vm
- implement dmenu background coloring according to the vm it's showing the menu for

2022-03-30 18:33 UTC, raffaeleflorio commented
Hi @jampe ,
Thank you for this contribution! The patch seems fine.
As last thing, can you sign your commits? Here you are a useful guide: https://www.qubes-os.org/doc/code-signing/

2022-03-30 21:15 UTC, jampe commented
Sure, commit is signed 👍

2022-03-31 06:24 UTC, raffaeleflorio requested changes

2022-03-31 06:24 UTC, raffaeleflorio commented on dmenu.patch
>  +    echo "usage: $0 dom0 | vms" >&2
@jampe can you update this function to reflect the new `vm` argument?

2022-03-31 07:12 UTC, raffaeleflorio approved these changes

2022-03-31 07:13 UTC, raffaeleflorio commented
Merged! 😄

2022-03-31 07:16 UTC, merged